# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Gareth Brown Dev & Sport Blog
tagline:          'Dev & Sport Blog'
description:      'A programmers dev and sporting blog'
url:              https://wonea.github.io/
baseurl:          /

author:
  name:           'Gareth Brown'
  url:            https://twitter.com/wonea

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wonea
